spring:
	datasource:
		url: jdbc:mysql://localhost:3306/sfg_dev
		username: sfg_dev_user
		password: Min#19057
		platform: mysql
	jpa:
		hibernate:
			ddl-auto: validate
		database-platform:vorg.hibernate.dialect.MySQL5InnoDBDialect
		database: mysql
		show-sql: true
		